Rnbeads integration and LMC intepreation functions
lutsik/MeDeCom pull request #12
Opened 2018-09-28 14:59 UTC by schmic05

This branch contains mainly three functions: associating LMC proportions with sample traits, GO enrichment analysis (GOstats package) for LMC-specific CpGs and LOLA enrichment for the same CpGs. The functions are ready to be called from within FactorViz and I'd thus like to have them in the master branch. Please have a look at the code and accept the pull request, if you are convinced.

2018-10-21 14:26 UTC, lutsik requested changes
Should we stick to a the scheme first used in RnBeads, i.e. first merging branches into devel and then merging into master as new (sub)releases? What do you think?

2018-10-21 15:10 UTC, lutsik commented on R/contribution_interpretation.R
> +link.to.traits <- function(medecom.set,cg_subset,K,lambda,rnb.set,test.fun=t.test){
Should we create more generic functions for this, which use phenotype data frames as input? RnBeads wrappers can be added on top?

2018-10-22 07:06 UTC, schmic05 commented
I like this idea! But then it will be entirely your resonsibility to merge the devel branch into the master branch as soon as you think it's worth merging.

2018-10-22 07:15 UTC, schmic05 commented on R/contribution_interpretation.R
> +#'                 \code{medecom.set} was computed or a data.frame of sample annotations (ann_S)
This is the case, we can either input and RnBSet or a data.frame. Anyway, the parameter name is missleading, will change it.

2018-10-22 09:43 UTC, closed without merging